# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php55-pdo_sqlite/Makefile 360588 2014-07-04 09:40:59Z tijl $

PORTREVISION=	1
CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-pdo_sqlite

.include "${MASTERDIR}/Makefile"
