# $FreeBSD: head/mail/rainloop/Makefile 385562 2015-05-06 20:34:12Z rodrigo $

PORTNAME=	rainloop
PKGNAMESUFFIX=	-community

COMMENT=	Modern and interactive webmail - community edition

MASTERDIR=	${.CURDIR}/../rainloop

DISTINFO_FILE=	${.CURDIR}/distinfo
PLIST=		${.CURDIR}/pkg-plist

EDITION=	community

CONFLICTS_INSTALL=	rainloop-[0-9]*

.include "${MASTERDIR}/Makefile"
