# Created by: Xin LI <delphij@FreeBSD.org>

CLIENT_ONLY=		yes

MASTERDIR=		${.CURDIR}/../openldap26-server

CONFGIGURE_ENV+=	ac_cv_lib_ssl_SSL_export_keying_material_early=yes

.include "${MASTERDIR}/Makefile"
