# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/textproc/php56-pspell/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-pspell

.include "${MASTERDIR}/Makefile"
