# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php5-sqlite3/Makefile 360738 2014-07-05 12:19:32Z tijl $

PORTREVISION=	1
CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-sqlite3

.include "${MASTERDIR}/Makefile"
