# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php56-sqlite3/Makefile 367268 2014-09-04 14:24:25Z ale $

PORTREVISION=	1
CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-sqlite3

.include "${MASTERDIR}/Makefile"
