# Created by: Niclas Zeising <zeising@FreeBSD.org>
# $FreeBSD: head/net-mgmt/nrpe-ssl/Makefile 424560 2016-10-24 10:18:50Z mat $

PKGNAMESUFFIX=	-ssl

COMMENT=	Nagios Remote Plugin Executor (SSL version)

CONFLICTS=	nrpe-2.*

OPTIONS_SLAVE=	SSL

MASTERDIR=		${.CURDIR}/../nrpe

.include "${MASTERDIR}/Makefile"
