# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/security/php55-mcrypt/Makefile 368418 2014-09-17 23:27:08Z amdmi3 $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-mcrypt

.include "${MASTERDIR}/Makefile"
