# Created by: Bermard Spil <brnrd@FreeBSD.org> 
# $FreeBSD$

PORTNAME=	cymruwhois
PORTVERSION=	1.0
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	brnrd@FreeBSD.org
COMMENT=	Client for the whois.cymru.com service

LICENSE=	MIT

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
