# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/textproc/php5-pspell/Makefile 360658 2014-07-04 20:28:31Z tijl $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-pspell

.include "${MASTERDIR}/Makefile"
