# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php55-sqlite3/Makefile 360738 2014-07-05 12:19:32Z tijl $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-sqlite3

.include "${MASTERDIR}/Makefile"
